// Pour le dev
// Pour ne pas appeler l'API de trop nombreuses fois et dépasser le quota

// 20220415120007
// https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&regionCode=FR&maxResults=20&key=AIzaSyC0ObYO_yxgMXEeOUohEnZGqDvQRXL3JuI

export const apiData = {
  kind: "youtube#videoListResponse",
  etag: "opeRD5oY51-npUE7sL65WSfSiLY",
  items: [
    {
      kind: "youtube#video",
      etag: "YCIhAYiD1qkPG4TEJhPXQ2-1kFc",
      id: "Q3Ps7a6JLaQ",
      snippet: {
        publishedAt: "2022-04-13T17:00:22Z",
        channelId: "UCV94nTgy_2Ypl8jBvT-HkfQ",
        title: "Notre rencontre, notre relation, on vous répond!",
        description:
          "Je pense que la vidéo était assez attendue, la voila!!\nSi vous voulez revoir Adil en vidéo, n’hésitez pas à dire en commentaires dans quel type de vidéo, je regarderai avec attention! \n\nInstagram Léna: https://instagram.com/lenoutsa?igshid=YmMyMTA2M2Y=\n\nInstagram Adil : https://instagram.com/adilrami?igshid=YmMyMTA2M2Y=",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/Q3Ps7a6JLaQ/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/Q3Ps7a6JLaQ/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/Q3Ps7a6JLaQ/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/Q3Ps7a6JLaQ/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/Q3Ps7a6JLaQ/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Lenoutsa",
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "Notre rencontre, notre relation, on vous répond!",
          description:
            "Je pense que la vidéo était assez attendue, la voila!!\nSi vous voulez revoir Adil en vidéo, n’hésitez pas à dire en commentaires dans quel type de vidéo, je regarderai avec attention! \n\nInstagram Léna: https://instagram.com/lenoutsa?igshid=YmMyMTA2M2Y=\n\nInstagram Adil : https://instagram.com/adilrami?igshid=YmMyMTA2M2Y=",
        },
      },
      contentDetails: {
        duration: "PT27M57S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "377266",
        likeCount: "18305",
        favoriteCount: "0",
        commentCount: "547",
      },
    },
    {
      kind: "youtube#video",
      etag: "h68pgO6YqLplIcU3mlmdc-OPyI4",
      id: "UT3FL6D_HTc",
      snippet: {
        publishedAt: "2022-04-13T15:43:48Z",
        channelId: "UCA9IJ0GhYcbSst7C6cQWrKw",
        title: "COMBIEN vaux-tu sur INTERNET ? 💰",
        description:
          "Simuler une journée entière de partage de données avec le site MesDatasEtMoi : https://www.mesdatasetmoi.fr/experience/une-journee-de-donnees (c'est rapide à faire - de 10 minutes !)\n@MAIF et @Mesdatasetmoi\n\nCombien coûte ta vie ?\nJusqu’à sa retraite, un français moyen va gagner environ 1.18M€ (nets). C’est moins que la valeur de ton corps : 30 millions de dollars, si on additionne la valeur de tes organes et substances biologiques, comme ton sang. Avec Internet, ton existence a encore pris de la valeur grâce… aux données ! Des gens sont prêts à acheter les tiennes à prix d’or. Mais sais-tu à combien ? \nTu connais le proverbe : si Internet est gratuit, c’est que c’est toi le produit.\nAlors on va t’expliquer tout ce qui peut se vendre sur toi et les dangers qu’il y a derrière\n\n00:00 Introduction\n00:25 Partie 1 : Quel est le prix de vos données personnelles ?\n03:32 Partie 2 : Ce que Google et Facebook savent de toi est effrayant\n07:18 Partie 3 : Peut-on vraiment ne pas partager ses données ?\n\n🐤 Twitter Antoine► https://twitter.com/Toitwane​​\n🐤 Twitter Mathart ► https://twitter.com/GuillaumeSaes\n🐤 Twitter Maxence ► https://twitter.com/Morgan_Edt\n🐤 Twitter Neoxys ► https://twitter.com/trash_neo_​​\n🐤 Twitter Zelrio ► https://twitter.com/Zelrio99\n\n▼▼ DÉROULE LA DESCRIPTION ▼▼\n\n💃 TikTok  ► https://www.tiktok.com/@trasheurs\n😂 Facebook ► https://www.facebook.com/trasheurs.videos/\n👀 Instagram ► https://www.instagram.com/trash_neo_/\n🎮 Discord ► https://discord.gg/YGAaDD6Cy2\n💸 Tipeee ► https://fr.tipeee.com/trash/",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/UT3FL6D_HTc/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/UT3FL6D_HTc/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/UT3FL6D_HTc/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Science Trash",
        tags: [
          "science",
          "data",
          "MAIF",
          "données",
          "valeur",
          "prix",
          "internet",
          "données personnelles",
          "personnelles",
          "data brokers",
          "cookies",
          "achat",
          "Google",
          "datas",
          "Facebook",
          "savoir",
          "pub",
          "marketing",
          "influencer",
          "personnaliser",
          "partager",
          "ses données",
          "algorithme",
          "informatique",
          "net",
          "pub ciblée",
          "technologie",
          "géolocalisation",
          "analyse",
          "personnalisation",
        ],
        categoryId: "28",
        liveBroadcastContent: "none",
        localized: {
          title: "COMBIEN vaux-tu sur INTERNET ? 💰",
          description:
            "Simuler une journée entière de partage de données avec le site MesDatasEtMoi : https://www.mesdatasetmoi.fr/experience/une-journee-de-donnees (c'est rapide à faire - de 10 minutes !)\n@MAIF et @Mesdatasetmoi\n\nCombien coûte ta vie ?\nJusqu’à sa retraite, un français moyen va gagner environ 1.18M€ (nets). C’est moins que la valeur de ton corps : 30 millions de dollars, si on additionne la valeur de tes organes et substances biologiques, comme ton sang. Avec Internet, ton existence a encore pris de la valeur grâce… aux données ! Des gens sont prêts à acheter les tiennes à prix d’or. Mais sais-tu à combien ? \nTu connais le proverbe : si Internet est gratuit, c’est que c’est toi le produit.\nAlors on va t’expliquer tout ce qui peut se vendre sur toi et les dangers qu’il y a derrière\n\n00:00 Introduction\n00:25 Partie 1 : Quel est le prix de vos données personnelles ?\n03:32 Partie 2 : Ce que Google et Facebook savent de toi est effrayant\n07:18 Partie 3 : Peut-on vraiment ne pas partager ses données ?\n\n🐤 Twitter Antoine► https://twitter.com/Toitwane​​\n🐤 Twitter Mathart ► https://twitter.com/GuillaumeSaes\n🐤 Twitter Maxence ► https://twitter.com/Morgan_Edt\n🐤 Twitter Neoxys ► https://twitter.com/trash_neo_​​\n🐤 Twitter Zelrio ► https://twitter.com/Zelrio99\n\n▼▼ DÉROULE LA DESCRIPTION ▼▼\n\n💃 TikTok  ► https://www.tiktok.com/@trasheurs\n😂 Facebook ► https://www.facebook.com/trasheurs.videos/\n👀 Instagram ► https://www.instagram.com/trash_neo_/\n🎮 Discord ► https://discord.gg/YGAaDD6Cy2\n💸 Tipeee ► https://fr.tipeee.com/trash/",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT10M3S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "308194",
        likeCount: "26846",
        favoriteCount: "0",
        commentCount: "659",
      },
    },
    {
      kind: "youtube#video",
      etag: "6LXNFwPMJuoIQGRCPj3vit1Bf-o",
      id: "C7v4yaUTPpA",
      snippet: {
        publishedAt: "2022-04-13T16:00:05Z",
        channelId: "UCSKdvgqdnj72_SLggp7BDTg",
        title:
          "Ce que le Z Event a permis d'accomplir : avec Zerator en Centrafrique",
        description:
          "Grâce à la générosité des communautés des streamers francophones, voici ce qui a été accompli. Le dernier Z Event a permis de récolter plus de 10 millions d'euros pour Action contre la faim. Brut a suivi Zerator en Centrafrique pour voir à quoi ces dons ont servi.\n\n💚 Voici tout ce que les dons du Z Event pour Action contre la faim vont permettre d'accomplir : https://www.actioncontrelafaim.org/a-la-une/a-quoi-vont-servir-les-dons-du-z-event/",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/C7v4yaUTPpA/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/C7v4yaUTPpA/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/C7v4yaUTPpA/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/C7v4yaUTPpA/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/C7v4yaUTPpA/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Brut",
        tags: [
          "brut",
          "z event",
          "zevent",
          "z lan",
          "zlan",
          "zerator",
          "dash",
          "centrafrique",
          "don",
          "2022",
          "2021",
          "best of",
          "twitch",
          "popcorn",
          "action contre la faim",
          "afrique",
          "africain",
          "croix rouge",
        ],
        categoryId: "25",
        liveBroadcastContent: "none",
        localized: {
          title:
            "Ce que le Z Event a permis d'accomplir : avec Zerator en Centrafrique",
          description:
            "Grâce à la générosité des communautés des streamers francophones, voici ce qui a été accompli. Le dernier Z Event a permis de récolter plus de 10 millions d'euros pour Action contre la faim. Brut a suivi Zerator en Centrafrique pour voir à quoi ces dons ont servi.\n\n💚 Voici tout ce que les dons du Z Event pour Action contre la faim vont permettre d'accomplir : https://www.actioncontrelafaim.org/a-la-une/a-quoi-vont-servir-les-dons-du-z-event/",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT16M",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "718799",
        likeCount: "42232",
        favoriteCount: "0",
        commentCount: "1658",
      },
    },
    {
      kind: "youtube#video",
      etag: "54_hnHPP32V-lq5CWChmbKNOsfI",
      id: "w4aUdQn0iZs",
      snippet: {
        publishedAt: "2022-04-12T16:00:00Z",
        channelId: "UCWnfDPdZw6A23UtuBpYBbAg",
        title: "Pourquoi cet arc est surpuissant ? (et trop dangereux)",
        description:
          "Je test un arc surpuissant, et un petit peu dangereux... \nNouveau drop de board biome : http://www.biomeskateboard.fr\n\nViens me voir sur insta : https://instagram.com/docnozman/\n\nMerci à Jean Michel Courty pour la relecture : https://www.youtube.com/channel/UCopqcajNZl96Oy3oeRQIk3g\n\nMontage / Illustration : https://bit.ly/2o1bwwM\nEcriture : https://www.youtube.com/c/LesRecapsduMonde\n\nMon matos :\nCaméra : http://amzn.to/2oBOE9n\nObjectif : http://amzn.to/2pbhj2T\nMicro : http://amzn.to/2oZYSBg\nLe micro cravate qui sauve des vies : http://amzn.to/2oql44s\nEclairage : http://amzn.to/2pbu91k // http://amzn.to/2o86pdp\nTrépied : http://amzn.to/2pbiVtl",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/w4aUdQn0iZs/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/w4aUdQn0iZs/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/w4aUdQn0iZs/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Dr Nozman",
        tags: ["dr nozman", "nozman", "arc"],
        categoryId: "28",
        liveBroadcastContent: "none",
        defaultLanguage: "fr",
        localized: {
          title: "Pourquoi cet arc est surpuissant ? (et trop dangereux)",
          description:
            "Je test un arc surpuissant, et un petit peu dangereux... \nNouveau drop de board biome : http://www.biomeskateboard.fr\n\nViens me voir sur insta : https://instagram.com/docnozman/\n\nMerci à Jean Michel Courty pour la relecture : https://www.youtube.com/channel/UCopqcajNZl96Oy3oeRQIk3g\n\nMontage / Illustration : https://bit.ly/2o1bwwM\nEcriture : https://www.youtube.com/c/LesRecapsduMonde\n\nMon matos :\nCaméra : http://amzn.to/2oBOE9n\nObjectif : http://amzn.to/2pbhj2T\nMicro : http://amzn.to/2oZYSBg\nLe micro cravate qui sauve des vies : http://amzn.to/2oql44s\nEclairage : http://amzn.to/2pbu91k // http://amzn.to/2o86pdp\nTrépied : http://amzn.to/2pbiVtl",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT13M39S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "751955",
        likeCount: "44315",
        favoriteCount: "0",
        commentCount: "2347",
      },
    },
    {
      kind: "youtube#video",
      etag: "OgEvLblyzQTUSuC3jANWmc8xJg4",
      id: "QigOZAIWyZQ",
      snippet: {
        publishedAt: "2022-04-13T16:04:38Z",
        channelId: "UC4Crt8VfMn3HXmZgVxlYdbQ",
        title: "JE BAS UN RECORD DU MONDE 🤩",
        description:
          "JE BAS UN RECORD DU MONDE 🤩\n⬇️ Viens me suivre sur les réseaux ⬇️\n\n📸 Instagram : arthurhennebo\nhttps://www.instagram.com/arthurhennebo\n\n🎵 TikTok : arthur.hennebo\nhttps://www.tiktok.com/@arthur.hennebo\n\n🎥 Chaîne Secondaire :\nhttps://www.youtube.com/c/ARTHUR20\n\n🎥 Chaîne Muscu : \nhttps://www.youtube.com/c/ArthurHennebo\n\n📧 Contact : arthur.hennebo@gmail.com",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/QigOZAIWyZQ/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/QigOZAIWyZQ/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/QigOZAIWyZQ/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "ARTHUR",
        tags: ["JE BAS UN RECORD DU MONDE", "Shorts"],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "JE BAS UN RECORD DU MONDE 🤩",
          description:
            "JE BAS UN RECORD DU MONDE 🤩\n⬇️ Viens me suivre sur les réseaux ⬇️\n\n📸 Instagram : arthurhennebo\nhttps://www.instagram.com/arthurhennebo\n\n🎵 TikTok : arthur.hennebo\nhttps://www.tiktok.com/@arthur.hennebo\n\n🎥 Chaîne Secondaire :\nhttps://www.youtube.com/c/ARTHUR20\n\n🎥 Chaîne Muscu : \nhttps://www.youtube.com/c/ArthurHennebo\n\n📧 Contact : arthur.hennebo@gmail.com",
        },
        defaultAudioLanguage: "fr-FR",
      },
      contentDetails: {
        duration: "PT36S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "307279",
        likeCount: "28055",
        favoriteCount: "0",
        commentCount: "258",
      },
    },
    {
      kind: "youtube#video",
      etag: "6l6rBh_wD73NALhGzTvZlTeKESA",
      id: "t544fg-jBlM",
      snippet: {
        publishedAt: "2022-04-13T16:12:24Z",
        channelId: "UCCxAWA2XC7LQDjxgYOnmJeA",
        title: "JULIEN BERT passe le BASTOS TEST!!!! (Un MALADE)",
        description:
          "Il fait une obsession je crois!!!\n\nJulien BERT: https://www.instagram.com/julienbert42/?hl=en\n\n\n\nMontage: https://www.instagram.com/elodiebsvc/?hl=en\n\nREJOINDRE LA CHAINE ET PROFITER DES AVANTAGES!!!\nhttps://www.youtube.com/channel/UCCxAWA2XC7LQDjxgYOnmJeA/join",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/t544fg-jBlM/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/t544fg-jBlM/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/t544fg-jBlM/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/t544fg-jBlM/sddefault.jpg",
            width: 640,
            height: 480,
          },
        },
        channelTitle: "Bastos",
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "JULIEN BERT passe le BASTOS TEST!!!! (Un MALADE)",
          description:
            "Il fait une obsession je crois!!!\n\nJulien BERT: https://www.instagram.com/julienbert42/?hl=en\n\n\n\nMontage: https://www.instagram.com/elodiebsvc/?hl=en\n\nREJOINDRE LA CHAINE ET PROFITER DES AVANTAGES!!!\nhttps://www.youtube.com/channel/UCCxAWA2XC7LQDjxgYOnmJeA/join",
        },
      },
      contentDetails: {
        duration: "PT22M37S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "522913",
        likeCount: "35416",
        favoriteCount: "0",
        commentCount: "804",
      },
    },
    {
      kind: "youtube#video",
      etag: "mrSZDMDF_AUHlmT6bcSilm9EZVs",
      id: "QAS1JV82Ajg",
      snippet: {
        publishedAt: "2022-04-13T16:55:09Z",
        channelId: "UCCU2Tvanl8gLaJ7pYDuIYkg",
        title: "COMMENT FAIRE PASSER LES MAUVAISES NOTES 😏",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/QAS1JV82Ajg/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/QAS1JV82Ajg/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/QAS1JV82Ajg/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "BATZAIR",
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title: "COMMENT FAIRE PASSER LES MAUVAISES NOTES 😏",
          description: "",
        },
      },
      contentDetails: {
        duration: "PT42S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "581683",
        likeCount: "83803",
        favoriteCount: "0",
        commentCount: "479",
      },
    },
    {
      kind: "youtube#video",
      etag: "o1K6sSgmEs1rPU9ZCrzXFayV7p8",
      id: "MD3Z6GLQrec",
      snippet: {
        publishedAt: "2022-04-12T21:40:17Z",
        channelId: "UCfj4kQ6_mYO5r4hzX5KloVw",
        title:
          "Résumé LDC : Miraculé, le Real sauvé par Benzema en prolongations contre Chelsea",
        description:
          "[📺 RÉSUMÉ VIDÉO] 🏆 #UCL #RMACFC \n🔥🔥🔥🔥 LE REAL EST EN DEMI-FINALE !!!!\n🤯 Chelsea pensait avoir retourné la situation en menant 3-0 mais un but de Rodrygo permet aux Madrilènes d'arracher les prolongations !\n🤷 Et qui d'autre que Benzema pour marquer le but de la qualification ?\n\n💻 Résumés, buts, articles, vidéos, ... ➡️ www.beinsports.com\n📱 Retrouvez-nous sur les réseaux sociaux :\n➡️ Facebook : https://www.facebook.com/beINSPORTSFrance\n➡️ Twitter : https://twitter.com/beinsports_FR\n➡️ Instagram : https://www.instagram.com/beinsports_fr/\n➡️ TikTok : https://www.tiktok.com/@beinsportsfr",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/MD3Z6GLQrec/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/MD3Z6GLQrec/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/MD3Z6GLQrec/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "beIN SPORTS France",
        tags: [
          "résumé",
          "highlights",
          "ligue",
          "des",
          "champions",
          "league",
          "uefa",
          "real",
          "de",
          "madrid",
          "rma",
          "chelsea",
          "foot",
          "football",
          "club",
          "fc",
          "ngolo",
          "kante",
          "karim",
          "benzema",
          "kb9",
          "timo",
          "werner",
          "edouard",
          "mendy",
          "vini",
          "vinicius",
          "junior",
          "jr",
          "luka",
          "modric",
          "ferland",
          "romelu",
          "lukaku",
          "lakaka",
          "thibaut",
          "courtois",
          "toni",
          "krooks",
          "casemiro",
          "kai",
          "havertz",
          "mason",
          "mount",
          "thiago",
          "silva",
          "antonio",
          "rudiger",
          "jorginho",
          "christian",
          "pulisic",
          "hakim",
          "ziyech",
          "cesar",
          "azpilicueta",
          "eduardo",
          "camavinga",
          "gareth",
          "bale",
        ],
        categoryId: "17",
        liveBroadcastContent: "none",
        defaultLanguage: "fr",
        localized: {
          title:
            "Résumé LDC : Miraculé, le Real sauvé par Benzema en prolongations contre Chelsea",
          description:
            "[📺 RÉSUMÉ VIDÉO] 🏆 #UCL #RMACFC \n🔥🔥🔥🔥 LE REAL EST EN DEMI-FINALE !!!!\n🤯 Chelsea pensait avoir retourné la situation en menant 3-0 mais un but de Rodrygo permet aux Madrilènes d'arracher les prolongations !\n🤷 Et qui d'autre que Benzema pour marquer le but de la qualification ?\n\n💻 Résumés, buts, articles, vidéos, ... ➡️ www.beinsports.com\n📱 Retrouvez-nous sur les réseaux sociaux :\n➡️ Facebook : https://www.facebook.com/beINSPORTSFrance\n➡️ Twitter : https://twitter.com/beinsports_FR\n➡️ Instagram : https://www.instagram.com/beinsports_fr/\n➡️ TikTok : https://www.tiktok.com/@beinsportsfr",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT3M5S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        regionRestriction: {
          allowed: [
            "BL",
            "FR",
            "GF",
            "GP",
            "MF",
            "MQ",
            "NC",
            "PF",
            "PM",
            "RE",
            "TF",
            "WF",
            "YT",
          ],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "948677",
        likeCount: "17449",
        favoriteCount: "0",
        commentCount: "1700",
      },
    },
    {
      kind: "youtube#video",
      etag: "_npAiMlfKengAbiemnvIpinGHhk",
      id: "G8rAw_WKf8E",
      snippet: {
        publishedAt: "2022-04-12T14:00:01Z",
        channelId: "UCroNr00O68n25IqSNapMK8w",
        title:
          "Stranger Things 4 | Bande-annonce officielle VF | Netflix France",
        description:
          "L'heure a sonné. Rendez-vous de l'autre côté.\r\nSTRANGER THINGS saison 4 vol. 1, le 27 mai, seulement sur Netflix.\r\n\r\nAbonnez-vous à la chaîne YouTube de Netflix France ! : http://bit.ly/NetflixFr_Abonner\r\n\r\nSUIVEZ-NOUS SUR NOS AUTRES RÉSEAUX SOCIAUX : \r\n\r\nFacebook : https://bit.ly/2HcfVaJ\r\nTwitter : https://bit.ly/385OYRx\r\nInstagram : https://bit.ly/31tanlo\r\n\r\nStranger Things 4 | Bande-annonce officielle VF | Netflix France\r\nhttps://youtube.com/NetflixFrance",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/G8rAw_WKf8E/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/G8rAw_WKf8E/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/G8rAw_WKf8E/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Netflix France",
        tags: [
          "stranger things",
          "stranger things 4",
          "onze",
          "eleven",
          "millie bobby brown",
          "mike wheeler",
          "finn wolfhard",
          "lucas sinclair",
          "caleb mclaughlin",
          "dustin",
          "gaten matarazzo",
          "noah schnapp",
          "will byers",
          "charlie heaton",
          "jonathan byers",
          "nancy wheeler",
          "natalia dyer",
          "hopper",
          "chief hopper",
          "david harbour",
          "maya hawke",
          "robin stranger things",
          "steve harrington",
          "joe keery",
          "joyce byers",
          "winona ryder",
          "sadie sink",
          "max stranger things",
          "hawkins",
          "eddie munson",
          "joseph quinn",
          "eduardo franco",
          "argyle",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title:
            "Stranger Things 4 | Bande-annonce officielle VF | Netflix France",
          description:
            "L'heure a sonné. Rendez-vous de l'autre côté.\r\nSTRANGER THINGS saison 4 vol. 1, le 27 mai, seulement sur Netflix.\r\n\r\nAbonnez-vous à la chaîne YouTube de Netflix France ! : http://bit.ly/NetflixFr_Abonner\r\n\r\nSUIVEZ-NOUS SUR NOS AUTRES RÉSEAUX SOCIAUX : \r\n\r\nFacebook : https://bit.ly/2HcfVaJ\r\nTwitter : https://bit.ly/385OYRx\r\nInstagram : https://bit.ly/31tanlo\r\n\r\nStranger Things 4 | Bande-annonce officielle VF | Netflix France\r\nhttps://youtube.com/NetflixFrance",
        },
        defaultAudioLanguage: "en-US",
      },
      contentDetails: {
        duration: "PT3M31S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "254697",
        likeCount: "12245",
        favoriteCount: "0",
        commentCount: "543",
      },
    },
    {
      kind: "youtube#video",
      etag: "CcjMyBV9PEFz29prDdNcX1cgCdI",
      id: "rwGiMkRDeDE",
      snippet: {
        publishedAt: "2022-04-13T11:02:57Z",
        channelId: "UCicJflaX_UIUfE8bS5rN0mQ",
        title:
          "24H ON VIT COMME DES MILLIONNAIRES !! ( budget illimités pour tous )! 😭 je suis ruiné …",
        description:
          "La famille tuche dans le luxe ! Ça promet d’être archi drôle 😂✨\n\nProfitez￼ bien de cette vidéo car il y en aura pas de similaire avant bien longtemps ! 😂\n\n￼ Like et abonne toi ! ♥️\n\nREJOINT NOUS ICI ☺️\n\n✅La chaîne de  lilou https://youtube.com/channel/UCbVR75driUEdTLDJ8DXZvOg\n\n❤️ Instagram : https://instagram.com/p/BxnLaAFIqZ3/\n\n❤️Instagram de Lilou et moi   : https://www.instagram.com/p/B7wIgA6i1hu/?igshid=1jsfm3l39yb7q\n\n❤️ tik tok Comédie  : http://vm.tiktok.com/duspnd/\nTik tok de Lilou : https://vm.tiktok.com/ZSbMLbAU/\n\n💕NEW TIKTOK SKINCARE MAKEUP \n : https://vm.tiktok.com/ZMesgFHTq/\n\nContact pro : contactloufitlove@gmail.com",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/rwGiMkRDeDE/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/rwGiMkRDeDE/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/rwGiMkRDeDE/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/rwGiMkRDeDE/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/rwGiMkRDeDE/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "loufitlove",
        tags: [
          "#drole",
          "#humour #rire",
          "#famille",
          "#famillygoal",
          "#loufitlove",
          "#comedie",
          "#liloufitlove",
          "#folie",
          "#challenge",
          "#prank",
          "#pranker",
          "#shorts",
          "#tiktok",
          "#new",
          "#loufitlovefamilly",
          "#newvideo",
          "#videodrole",
          "#nimp",
          "#luxe",
          "#luxury",
          "#shopping",
          "#24h",
          "#vlog",
          "#familles",
          "#argent",
          "#chanel",
          "#gucci",
          "#disneyvillage",
          "#paris",
          "#palace",
          "#riche",
          "#millionaire",
          "#caviar",
        ],
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title:
            "24H ON VIT COMME DES MILLIONNAIRES !! ( budget illimités pour tous )! 😭 je suis ruiné …",
          description:
            "La famille tuche dans le luxe ! Ça promet d’être archi drôle 😂✨\n\nProfitez￼ bien de cette vidéo car il y en aura pas de similaire avant bien longtemps ! 😂\n\n￼ Like et abonne toi ! ♥️\n\nREJOINT NOUS ICI ☺️\n\n✅La chaîne de  lilou https://youtube.com/channel/UCbVR75driUEdTLDJ8DXZvOg\n\n❤️ Instagram : https://instagram.com/p/BxnLaAFIqZ3/\n\n❤️Instagram de Lilou et moi   : https://www.instagram.com/p/B7wIgA6i1hu/?igshid=1jsfm3l39yb7q\n\n❤️ tik tok Comédie  : http://vm.tiktok.com/duspnd/\nTik tok de Lilou : https://vm.tiktok.com/ZSbMLbAU/\n\n💕NEW TIKTOK SKINCARE MAKEUP \n : https://vm.tiktok.com/ZMesgFHTq/\n\nContact pro : contactloufitlove@gmail.com",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT37M1S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "169541",
        likeCount: "13739",
        favoriteCount: "0",
        commentCount: "1329",
      },
    },
    {
      kind: "youtube#video",
      etag: "UcvgEoqVkoNYv7eOGe24YOAP3Ak",
      id: "zR5DoUUovc0",
      snippet: {
        publishedAt: "2022-04-12T22:00:11Z",
        channelId: "UCdAHaWcKdpbT5XkN2Er6BUQ",
        title: "『ONE PIECE FILM RED』特報 Teaser Trailer 2／8月6日（土）公開",
        description:
          '『ONE PIECE FILM RED』 2022年8月6日（土）公開！ \n物語のカギとなるのは、“歌声”と“赤髪”―。 \n総合プロデューサー・尾田栄一郎で贈る　待望のFILMシリーズ第4弾 \n\n公式サイト　https://www.onepiece-film.jp/ \n公式Twitter　https://twitter.com/OP_FILMRED \n\n【ストーリー】\n世界で最も愛されている歌手、ウタ。\n素性を隠したまま発信するその歌声は”別次元”と評されていた。\nそんな彼女が初めて公の前に姿を現すライブが開催される。\n色めき立つ海賊たち、目を光らせる海軍、\nそして何も知らずにただ彼女の歌声を楽しみにきた\nルフィ率いる麦わらの一味たち、\nありとあらゆるウタファンが会場を埋め尽くす中、\n今まさに全世界待望の歌声が響き渡ろうとしていた。\n\n原作・総合プロデューサー：尾田栄一郎　\n監督：谷口悟朗　脚本：黒岩勉\nキャラクターデザイン・総作画監督：佐藤雅将　美術監督・美術設定：加藤浩\n色彩設計：横山さよ子　CGディレクター：川崎健太郎　撮影監督：江間常高　\n製作担当：吉田智哉\n\n出演：田中真弓　中井和哉　岡村明美　山口勝平　平田広明　大谷育江　山口由里子　\n矢尾一樹　チョー　宝亀克寿　／　池田秀一\n\n©尾田栄一郎／2022「ワンピース」製作委員会　　\n配給：東映　\n\n\n#ONEPIECE #ワンピース ＃OP_FILMRED #ルフィ #LUFFY \n#尾田栄一郎 #谷口悟朗 ＃黒岩勉\n\n\n“Singing voice” and “Red-haird” are the keys to the story.\n\nPresents by General Producer Eiichiro Oda, the long-awaited 4th FILM series finally set to go.\n\nOfficial web site: https://www.onepiece-film.jp/en/\nOfficial Twitter: https://twitter.com/OP_FILMRED\n\n【Synopsis】\nUta — the most beloved singer in the world. \nHer voice, which she sings with while concealing her true identity, has been described as “otherworldly.”\nShe will appear in public for the first time at a live concert.\nAs the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound.\nThe story begins with the shocking fact that she is "Shanks\' daughter.”\n\nAuthor and General Producer: Eiichiro Oda\nDirector: Goro Taniguchi \nScreenplay: Tsutomu Kuroiwa \nCharacter Design & General Animation Director: Masayuki SATO\nArt Director & Concept Art: Hiroshi Kato\nColor Designer: Sayoko Yokoyama\nCG Director: Kentaro Kawasaki\nPhotography Director: Tsunetaka Ema\nProduction Manager: Tomoya Yoshida\n\nJapanese film distributor: Toei \n© Eiichiro Oda/2022 "One Piece" production committee \n\n#ONEPIECE #FILMRED #OP_FILMRED #LUFFY #EiichiroOda #GoroTaniguchi #TsutomuKuroiwa #원피스 #航海王 #วันพีซ #वनपीस   #فلمونبيس',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/zR5DoUUovc0/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/zR5DoUUovc0/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/zR5DoUUovc0/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/zR5DoUUovc0/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/zR5DoUUovc0/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "ONE PIECE公式YouTubeチャンネル",
        categoryId: "1",
        liveBroadcastContent: "none",
        localized: {
          title:
            "『ONE PIECE FILM RED』特報 Teaser Trailer 2／8月6日（土）公開",
          description:
            '『ONE PIECE FILM RED』 2022年8月6日（土）公開！ \n物語のカギとなるのは、“歌声”と“赤髪”―。 \n総合プロデューサー・尾田栄一郎で贈る　待望のFILMシリーズ第4弾 \n\n公式サイト　https://www.onepiece-film.jp/ \n公式Twitter　https://twitter.com/OP_FILMRED \n\n【ストーリー】\n世界で最も愛されている歌手、ウタ。\n素性を隠したまま発信するその歌声は”別次元”と評されていた。\nそんな彼女が初めて公の前に姿を現すライブが開催される。\n色めき立つ海賊たち、目を光らせる海軍、\nそして何も知らずにただ彼女の歌声を楽しみにきた\nルフィ率いる麦わらの一味たち、\nありとあらゆるウタファンが会場を埋め尽くす中、\n今まさに全世界待望の歌声が響き渡ろうとしていた。\n\n原作・総合プロデューサー：尾田栄一郎　\n監督：谷口悟朗　脚本：黒岩勉\nキャラクターデザイン・総作画監督：佐藤雅将　美術監督・美術設定：加藤浩\n色彩設計：横山さよ子　CGディレクター：川崎健太郎　撮影監督：江間常高　\n製作担当：吉田智哉\n\n出演：田中真弓　中井和哉　岡村明美　山口勝平　平田広明　大谷育江　山口由里子　\n矢尾一樹　チョー　宝亀克寿　／　池田秀一\n\n©尾田栄一郎／2022「ワンピース」製作委員会　　\n配給：東映　\n\n\n#ONEPIECE #ワンピース ＃OP_FILMRED #ルフィ #LUFFY \n#尾田栄一郎 #谷口悟朗 ＃黒岩勉\n\n\n“Singing voice” and “Red-haird” are the keys to the story.\n\nPresents by General Producer Eiichiro Oda, the long-awaited 4th FILM series finally set to go.\n\nOfficial web site: https://www.onepiece-film.jp/en/\nOfficial Twitter: https://twitter.com/OP_FILMRED\n\n【Synopsis】\nUta — the most beloved singer in the world. \nHer voice, which she sings with while concealing her true identity, has been described as “otherworldly.”\nShe will appear in public for the first time at a live concert.\nAs the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound.\nThe story begins with the shocking fact that she is "Shanks\' daughter.”\n\nAuthor and General Producer: Eiichiro Oda\nDirector: Goro Taniguchi \nScreenplay: Tsutomu Kuroiwa \nCharacter Design & General Animation Director: Masayuki SATO\nArt Director & Concept Art: Hiroshi Kato\nColor Designer: Sayoko Yokoyama\nCG Director: Kentaro Kawasaki\nPhotography Director: Tsunetaka Ema\nProduction Manager: Tomoya Yoshida\n\nJapanese film distributor: Toei \n© Eiichiro Oda/2022 "One Piece" production committee \n\n#ONEPIECE #FILMRED #OP_FILMRED #LUFFY #EiichiroOda #GoroTaniguchi #TsutomuKuroiwa #원피스 #航海王 #วันพีซ #वनपीस   #فلمونبيس',
        },
        defaultAudioLanguage: "ja",
      },
      contentDetails: {
        duration: "PT46S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "6887300",
        likeCount: "201936",
        favoriteCount: "0",
        commentCount: "13987",
      },
    },
    {
      kind: "youtube#video",
      etag: "DqNrxxKo_YDB-cS9Z_dbVM2h79E",
      id: "VrntY8jMb40",
      snippet: {
        publishedAt: "2022-04-13T09:30:09Z",
        channelId: "UCFmN0sav0nBd0gsaPwrCFtA",
        title: "Satan & Blagues de jeunesse 👿 - Seb Mellia",
        description:
          '"Oh c\'est juste Satan..." 🤣\n\nAbonne toi à ma chaine ! 🌟\n\n▶ Et retrouvez moi en spectacle à Paris ici :\nhttp://bit.ly/SebParis \n\n▶▶ Et en tournée en France ici :\nhttp://bit.ly/SebTournée\n\nMais aussi ici :\n▶Facebook : https://goo.gl/an9IC9\n▶Twitter : https://goo.gl/o6EHgr\n▶ Instagram : https://www.instagram.com/sebmellia/\n\n▶http://www.SebMellia.fr\n\n▶ Ma boutique en ligne, goodies etc... ici :\nhttp://bit.ly/BoutiqueSebMellia',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/VrntY8jMb40/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/VrntY8jMb40/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/VrntY8jMb40/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/VrntY8jMb40/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/VrntY8jMb40/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "SebMellia",
        tags: [
          "Seb Mellia",
          "Humour",
          "stand up",
          "sketch",
          "one man show",
          "spectacle",
          "vlog",
          "podcast",
          "4 comiques dans le vent",
          "Seb Mellia ne perd jamais",
          "impro",
          "show",
          "drole",
          "humoriste",
          "divertissement",
          "émission",
        ],
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title: "Satan & Blagues de jeunesse 👿 - Seb Mellia",
          description:
            '"Oh c\'est juste Satan..." 🤣\n\nAbonne toi à ma chaine ! 🌟\n\n▶ Et retrouvez moi en spectacle à Paris ici :\nhttp://bit.ly/SebParis \n\n▶▶ Et en tournée en France ici :\nhttp://bit.ly/SebTournée\n\nMais aussi ici :\n▶Facebook : https://goo.gl/an9IC9\n▶Twitter : https://goo.gl/o6EHgr\n▶ Instagram : https://www.instagram.com/sebmellia/\n\n▶http://www.SebMellia.fr\n\n▶ Ma boutique en ligne, goodies etc... ici :\nhttp://bit.ly/BoutiqueSebMellia',
        },
      },
      contentDetails: {
        duration: "PT8M48S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "104469",
        likeCount: "4976",
        favoriteCount: "0",
        commentCount: "132",
      },
    },
    {
      kind: "youtube#video",
      etag: "9pQPY545SKdNG9QB5veygQ-lFNc",
      id: "KhvWP1XPDRw",
      snippet: {
        publishedAt: "2022-04-13T15:30:02Z",
        channelId: "UC_z2DJwwcpIxhtkxM9BX9VA",
        title:
          "Redouane Bougheraba : La vraie vie parisienne - Paris VS Province - Comédie+",
        description:
          "La chaîne COMEDIE+ est disponible avec CANAL+.\n\nRetrouvez COMEDIE+ la plus grande salle de spectacle d'humour, sur toutes nos plateformes : \n\nmyCANAL : https://www.canalplus.com/chaines/comedie\nFacebook : https://facebook.com/comedieplus\nTwitter : https://twitter.com/Comedie_plus\nYoutube : https://youtube.com/comediepluslachaine\nDailymotion : https://dailymotion.com/comedie\n\nComédie+, Restons de bon humour !",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/KhvWP1XPDRw/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/KhvWP1XPDRw/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/KhvWP1XPDRw/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/KhvWP1XPDRw/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/KhvWP1XPDRw/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Comédie+",
        tags: [
          "CANAL",
          "CANAL+",
          "COMEDIE",
          "COMEDIE+",
          "COMIQUE",
          "DROLE",
          "HUMORISTE",
          "ONE MAN SHOW",
          "ONE WOMAN SHOW",
          "PARODIE",
          "RIRE",
          "SCENE",
          "STAND UP",
          "THEATRE",
          "humour",
          "spectacle",
          "standup",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title:
            "Redouane Bougheraba : La vraie vie parisienne - Paris VS Province - Comédie+",
          description:
            "La chaîne COMEDIE+ est disponible avec CANAL+.\n\nRetrouvez COMEDIE+ la plus grande salle de spectacle d'humour, sur toutes nos plateformes : \n\nmyCANAL : https://www.canalplus.com/chaines/comedie\nFacebook : https://facebook.com/comedieplus\nTwitter : https://twitter.com/Comedie_plus\nYoutube : https://youtube.com/comediepluslachaine\nDailymotion : https://dailymotion.com/comedie\n\nComédie+, Restons de bon humour !",
        },
      },
      contentDetails: {
        duration: "PT10M27S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "50398",
        likeCount: "838",
        favoriteCount: "0",
        commentCount: "27",
      },
    },
    {
      kind: "youtube#video",
      etag: "7qP3qUp06X-evXNdUVHmAJ3Ed8U",
      id: "6j928wBZ_Bo",
      snippet: {
        publishedAt: "2022-04-13T09:00:07Z",
        channelId: "UCN2bQLTTvNPZWCWU5TYghKA",
        title: "Jessi (제시) - 'ZOOM' MV",
        description:
          "Jessi (제시) - 'ZOOM' MV\n\nMV Executive Producer: P NATION \nMV Director: 하이퀄리티피쉬 (HIGHQUALITYFISH)\nComposed by: PSY, 유건형, bayb\nLyrics by: Jessi, PSY, bobblehead, 염따\nArranged by: 유건형, bayb\nMixed by: Stay Tuned @Stay Tuned Studio\nMastered by: 권남우 @821 Sound Mastering\n\n* ‘ZOOM’ is now available on all streaming platforms including Apple Music & Spotify. \n\n🎧 Spotify : https://spoti.fi/3Ob775S\n🎧 YouTube Music : https://bit.ly/3xpqxyi\n🎧 iTunes & Apple Music : https://apple.co/3uBixIm\n🎧 Melon : https://bit.ly/37HfSnB\n🎧 Genie : https://bit.ly/3KDjtlp \n🎧 FLO : https://bit.ly/38OjFA8 \n🎧 Bugs : https://bit.ly/3rlX6Jo \n🎧 VIBE : https://bit.ly/3JEm6SC\n\n- Jessi Official YouTube: https://www.youtube.com/jessiofficial\n- Jessi Official Instagram: https://www.instagram.com/jessicah_o\n- Jessi Official Facebook: https://www.facebook.com/jessihomusic \n- Jessi Official Tiktok: https://www.tiktok.com/@itsjessibaby \n- Jessi Official Weibo: https://weibo.com/u/7107198887\n- Jessi Official Douyin: https://v.douyin.com/e89syA5\n\n-  P NATION Official Instagram: https://www.instagram.com/pnation.official\n-  P NATION Official Facebook: https://www.facebook.com/pnation.official\n-  P NATION Official Twitter: https://twitter.com/OfficialPnation\n-  P NATION Official Weibo: https://weibo.com/pnation\n\n#Jessi #제시 #ZOOM #줌 #PNATION #피네이션\n\nCopyrights 2022 ⓒ P NATION All Rights Reserved",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/6j928wBZ_Bo/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/6j928wBZ_Bo/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/6j928wBZ_Bo/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Jessi",
        tags: [
          "Jessi",
          "JESSI",
          "제시",
          "ZOOM",
          "zoom",
          "줌",
          "Zoom",
          "MV",
          "피네이션",
          "PNATION",
          "P NATION",
          "p nation",
          "la chica",
          "라치카",
          "La Chica",
          "LACHICA",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "Jessi (제시) - 'ZOOM' MV",
          description:
            "Jessi (제시) - 'ZOOM' MV\n\nMV Executive Producer: P NATION \nMV Director: 하이퀄리티피쉬 (HIGHQUALITYFISH)\nComposed by: PSY, 유건형, bayb\nLyrics by: Jessi, PSY, bobblehead, 염따\nArranged by: 유건형, bayb\nMixed by: Stay Tuned @Stay Tuned Studio\nMastered by: 권남우 @821 Sound Mastering\n\n* ‘ZOOM’ is now available on all streaming platforms including Apple Music & Spotify. \n\n🎧 Spotify : https://spoti.fi/3Ob775S\n🎧 YouTube Music : https://bit.ly/3xpqxyi\n🎧 iTunes & Apple Music : https://apple.co/3uBixIm\n🎧 Melon : https://bit.ly/37HfSnB\n🎧 Genie : https://bit.ly/3KDjtlp \n🎧 FLO : https://bit.ly/38OjFA8 \n🎧 Bugs : https://bit.ly/3rlX6Jo \n🎧 VIBE : https://bit.ly/3JEm6SC\n\n- Jessi Official YouTube: https://www.youtube.com/jessiofficial\n- Jessi Official Instagram: https://www.instagram.com/jessicah_o\n- Jessi Official Facebook: https://www.facebook.com/jessihomusic \n- Jessi Official Tiktok: https://www.tiktok.com/@itsjessibaby \n- Jessi Official Weibo: https://weibo.com/u/7107198887\n- Jessi Official Douyin: https://v.douyin.com/e89syA5\n\n-  P NATION Official Instagram: https://www.instagram.com/pnation.official\n-  P NATION Official Facebook: https://www.facebook.com/pnation.official\n-  P NATION Official Twitter: https://twitter.com/OfficialPnation\n-  P NATION Official Weibo: https://weibo.com/pnation\n\n#Jessi #제시 #ZOOM #줌 #PNATION #피네이션\n\nCopyrights 2022 ⓒ P NATION All Rights Reserved",
        },
        defaultAudioLanguage: "ko",
      },
      contentDetails: {
        duration: "PT3M3S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "4231004",
        likeCount: "616725",
        favoriteCount: "0",
        commentCount: "22246",
      },
    },
    {
      kind: "youtube#video",
      etag: "wf12Q8XQDMyPPuODPsBGTK95xjU",
      id: "SwgZrmKIInk",
      snippet: {
        publishedAt: "2022-04-13T15:00:15Z",
        channelId: "UC2myPsCYty0_fzW-VvkF-aA",
        title:
          "MARRE DE MA CALVITIE, JE VAIS EN TURQUIE POUR FAIRE UNE GREFFE DE CHEVEUX !",
        description:
          "⦁ MON PARTENAIRE « PROZIS » :\n👉 CODE PROMO  « GOD10 » utilisable sur http://www.prozis.com/l9S\nRÉDUCTION de 10 % + CADEAUX OFFERTS TOUTES LES SEMAINES + LIVRAISON OFFERTE\nJe modifie souvent les cadeaux liés à mon code, pense à l'utiliser régulièrement ! 🌴\n\n⦁ MA MARQUE DE VÊTEMENTS « ZVES » :\n👉  CODE PROMO  « GOD10 » pour une réduction de 10 % sur l'ensemble de mon site https://zvesapparel.com/\n\n⦁ POUR SOUSCRIRE À MA CHAÎNE : \n👉 https://www.youtube.com/channel/UC2myPsCYty0_fzW-VvkF-aA/join\nBon ça coûte 5 balles par mois certes, mais sache que ce geste constitue un énorme soutien pour moi. Toute participation de ta part m'aidera à financer de gros projet style \"GOD OF\" ou \"GenetiX. Je te remercie par avance 🌴\n#Calvitie #Turquie\n\n___________________________________________________________________________________\n\n- DEVIENS un C L A C H E U R en cliquant ici : goo.gl/kqbLHv\n\n- I N S T A G R A M : https://instagram.com/fromhumantogod/\n\n- T W I T CH : https://www.twitch.tv/efkanknz\n\n- T W I T T E R : https://twitter.com/fromhumantogod/\n\n- F A C E B O O K : https://www.facebook.com/HumanAndGod/\n\n___________________________________________________________________________________\nYouTube: bellahairclinic \nBilan Whatsapp: +90 535 685 83 93\nhttps://www.instagram.com/ozgur_bey\n___________________________________________________________________________________\n\nRéalisation et montage : https://www.okamedia.fr/\nMiniature : https://www.okamedia.fr/",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/SwgZrmKIInk/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/SwgZrmKIInk/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/SwgZrmKIInk/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/SwgZrmKIInk/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/SwgZrmKIInk/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "FromHumanToGod",
        tags: [
          "musculation",
          "efkan",
          "sèche",
          "force",
          "pectoraux",
          "abdo",
          "sixpack",
          "prozis",
          "zves",
          "kurnaz",
          "gazoile",
          "prise de masse",
          "sport",
          "nutrition",
          "genetix",
          "transformation",
          "turquie",
          "calvitie",
          "greffe de cheveux",
          "implant capillaire",
        ],
        categoryId: "17",
        liveBroadcastContent: "none",
        localized: {
          title:
            "MARRE DE MA CALVITIE, JE VAIS EN TURQUIE POUR FAIRE UNE GREFFE DE CHEVEUX !",
          description:
            "⦁ MON PARTENAIRE « PROZIS » :\n👉 CODE PROMO  « GOD10 » utilisable sur http://www.prozis.com/l9S\nRÉDUCTION de 10 % + CADEAUX OFFERTS TOUTES LES SEMAINES + LIVRAISON OFFERTE\nJe modifie souvent les cadeaux liés à mon code, pense à l'utiliser régulièrement ! 🌴\n\n⦁ MA MARQUE DE VÊTEMENTS « ZVES » :\n👉  CODE PROMO  « GOD10 » pour une réduction de 10 % sur l'ensemble de mon site https://zvesapparel.com/\n\n⦁ POUR SOUSCRIRE À MA CHAÎNE : \n👉 https://www.youtube.com/channel/UC2myPsCYty0_fzW-VvkF-aA/join\nBon ça coûte 5 balles par mois certes, mais sache que ce geste constitue un énorme soutien pour moi. Toute participation de ta part m'aidera à financer de gros projet style \"GOD OF\" ou \"GenetiX. Je te remercie par avance 🌴\n#Calvitie #Turquie\n\n___________________________________________________________________________________\n\n- DEVIENS un C L A C H E U R en cliquant ici : goo.gl/kqbLHv\n\n- I N S T A G R A M : https://instagram.com/fromhumantogod/\n\n- T W I T CH : https://www.twitch.tv/efkanknz\n\n- T W I T T E R : https://twitter.com/fromhumantogod/\n\n- F A C E B O O K : https://www.facebook.com/HumanAndGod/\n\n___________________________________________________________________________________\nYouTube: bellahairclinic \nBilan Whatsapp: +90 535 685 83 93\nhttps://www.instagram.com/ozgur_bey\n___________________________________________________________________________________\n\nRéalisation et montage : https://www.okamedia.fr/\nMiniature : https://www.okamedia.fr/",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT18M23S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "100375",
        likeCount: "6113",
        favoriteCount: "0",
        commentCount: "569",
      },
    },
    {
      kind: "youtube#video",
      etag: "8rhO-xmW1v-qUXo6DoCvWl-zpys",
      id: "cSE9r9eSjJk",
      snippet: {
        publishedAt: "2022-04-13T21:18:15Z",
        channelId: "UCfj4kQ6_mYO5r4hzX5KloVw",
        title:
          "Résumé LDC : Dans un match fou, Liverpool écarte Benfica pour accéder à la demi-finale",
        description:
          "[📺 RÉSUMÉ VIDÉO] 🏆 #UCL #LIVSLB \n👏👏👏 Liverpool fait le job et concède le nul 3-3 contre Benfica pour filer en demi-finale (6-4 cumulé) !\n💪 Konaté et Firmino (x2) ont marqué pour les Reds, Ramos et Yaremchuk ont sauvé l'honneur des Portugais !\n👀 Les Reds retrouveront Villarreal dans le dernier carré !\n\n💻 Résumés, buts, articles, vidéos, ... ➡️ www.beinsports.com\n📱 Retrouvez-nous sur les réseaux sociaux :\n➡️ Facebook : https://www.facebook.com/beINSPORTSFrance\n➡️ Twitter : https://twitter.com/beinsports_FR\n➡️ Instagram : https://www.instagram.com/beinsports_fr/\n➡️ TikTok : https://www.tiktok.com/@beinsportsfr",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/cSE9r9eSjJk/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/cSE9r9eSjJk/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/cSE9r9eSjJk/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "beIN SPORTS France",
        tags: [
          "résumé",
          "highlights",
          "liverpool",
          "fc",
          "foot",
          "football",
          "club",
          "benfica",
          "lisbon",
          "ligue",
          "des",
          "champions",
          "league",
          "mohamed",
          "salah",
          "roberto",
          "firmino",
          "luis",
          "diaz",
          "alisson",
          "becker",
          "darwin",
          "nunez",
          "ibrahima",
          "konate",
          "diogo",
          "jota",
          "yaremchuk",
          "goncalo",
          "ramos",
          "villarreal",
          "sadio",
          "mane",
          "virgil",
          "van",
          "dijk",
          "fabinho",
          "andrew",
          "robertson",
          "kostas",
          "tsimikas",
          "trent",
          "alexander",
          "arnold",
          "joel",
          "matip",
        ],
        categoryId: "17",
        liveBroadcastContent: "none",
        defaultLanguage: "fr",
        localized: {
          title:
            "Résumé LDC : Dans un match fou, Liverpool écarte Benfica pour accéder à la demi-finale",
          description:
            "[📺 RÉSUMÉ VIDÉO] 🏆 #UCL #LIVSLB \n👏👏👏 Liverpool fait le job et concède le nul 3-3 contre Benfica pour filer en demi-finale (6-4 cumulé) !\n💪 Konaté et Firmino (x2) ont marqué pour les Reds, Ramos et Yaremchuk ont sauvé l'honneur des Portugais !\n👀 Les Reds retrouveront Villarreal dans le dernier carré !\n\n💻 Résumés, buts, articles, vidéos, ... ➡️ www.beinsports.com\n📱 Retrouvez-nous sur les réseaux sociaux :\n➡️ Facebook : https://www.facebook.com/beINSPORTSFrance\n➡️ Twitter : https://twitter.com/beinsports_FR\n➡️ Instagram : https://www.instagram.com/beinsports_fr/\n➡️ TikTok : https://www.tiktok.com/@beinsportsfr",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT9M9S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        regionRestriction: {
          allowed: [
            "BL",
            "FR",
            "GF",
            "GP",
            "MF",
            "MQ",
            "NC",
            "PF",
            "PM",
            "RE",
            "TF",
            "WF",
            "YT",
          ],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "640171",
        likeCount: "13582",
        favoriteCount: "0",
        commentCount: "632",
      },
    },
    {
      kind: "youtube#video",
      etag: "qGWNR6Y7ZGQPiUxFa1z8zbr7j4o",
      id: "P4Agi0k6sQY",
      snippet: {
        publishedAt: "2022-04-13T14:40:18Z",
        channelId: "UC6y5gRz-d1YhBKTKv6QzKAw",
        title:
          "J’ai testé 10 LIFES HACK TIKTOK qui sont INTERDITS sur la SAISON 2 de Fortnite (ça marche)",
        description:
          "▶︎ LIKEZ 👍 et ABONNEZ VOUS 🔔 la famille ❤️\n\nJ’ai testé 10 LIFES HACK TIKTOK qui sont INTERDITS sur la SAISON 2 de Fortnite (ça marche)\n\nDans cette vidéo sur Fortnite, j'ai testé 10 lifes hacks de la saison 2 du chapitre 3 ! Briser les mythes de Fortnite que j'ai vus sur TikTok ! Des NOUVEAUX LIFES HACKS de Fortnite et je vais casser les plus fous pour vous ! 🤯\n\n🌐 RÉSEAUX SOCIAUX 🌐\n➔ Mon insta: https://www.instagram.com/naha_ytb/\n➔ Mon twitter: https://twitter.com/NahaBendero\n\n📩 contact business ➔ naha@rachimedia.com\n\n#troll​​​​ #trollfortnite​​​​ #prankfortnite",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/P4Agi0k6sQY/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/P4Agi0k6sQY/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/P4Agi0k6sQY/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/P4Agi0k6sQY/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/P4Agi0k6sQY/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Naha",
        tags: [
          "gaming",
          "fortnite",
          "fortnite chapitre 3",
          "life hack",
          "life hack fortnite",
          "life hack tiktok",
          "j'ai testé des lifes hack tiktok",
          "glitch tiktok",
          "secret fortnite",
          "mythe fortnite",
          "boss secret",
          "hack fortnite",
          "défilé fortnite",
          "casser fortnite",
          "naha",
        ],
        categoryId: "20",
        liveBroadcastContent: "none",
        defaultLanguage: "fr",
        localized: {
          title:
            "J’ai testé 10 LIFES HACK TIKTOK qui sont INTERDITS sur la SAISON 2 de Fortnite (ça marche)",
          description:
            "▶︎ LIKEZ 👍 et ABONNEZ VOUS 🔔 la famille ❤️\n\nJ’ai testé 10 LIFES HACK TIKTOK qui sont INTERDITS sur la SAISON 2 de Fortnite (ça marche)\n\nDans cette vidéo sur Fortnite, j'ai testé 10 lifes hacks de la saison 2 du chapitre 3 ! Briser les mythes de Fortnite que j'ai vus sur TikTok ! Des NOUVEAUX LIFES HACKS de Fortnite et je vais casser les plus fous pour vous ! 🤯\n\n🌐 RÉSEAUX SOCIAUX 🌐\n➔ Mon insta: https://www.instagram.com/naha_ytb/\n➔ Mon twitter: https://twitter.com/NahaBendero\n\n📩 contact business ➔ naha@rachimedia.com\n\n#troll​​​​ #trollfortnite​​​​ #prankfortnite",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT9M15S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "82350",
        likeCount: "5498",
        favoriteCount: "0",
        commentCount: "269",
      },
    },
    {
      kind: "youtube#video",
      etag: "FYJ1gB9Yx0pAVjNfEikv5PbcexQ",
      id: "rl4QZL9SuDk",
      snippet: {
        publishedAt: "2022-04-13T15:00:23Z",
        channelId: "UCJV7nmu40dh90vz4e7YAwoQ",
        title: "Juliette Armanet - Tu me Play (Clip Officiel)",
        description:
          "Nouvel album « Brûler le feu » maintenant disponible partout ❤️‍🔥https://lnk.to/JA-FeuID ❤️‍🔥\n \nS’abonner à la chaîne YouTube de Juliette : https://JulietteArmanet.lnk.to/abo-ytID\nInstagram : https://www.instagram.com/juliettearmanet\nFacebook : https://www.facebook.com/JulietteArmanet\nTwitter : https://twitter.com/juliettearmanet\nVinyle, CD, vêtements et accessoires : https://juliettearmanet.store/\n \n \nPRODUCTION - Caviar Paris:\nDirector : J.A.C.K\nExecutive Producer : Florent Haëse\nLine Producer  : Pierre Signoret\nChoregrapher : Carine Charaire\nCoach Roller : Rym Senoussi\nProduction Coordinator : Regine Yoba\nProduction Assistant : Manon Evrols\nProduction Assistant : Anna-Eva Sieger\n \n \nPRODUCTION SERVICE - Slime:\nExecutive Producer : Laia Vidal\nProducer : Imma Gutiérrez\n1st AD : Emilio Pérez\nLine Producer : Gemma Monzó\nProduction coordinator : Rocio Saiz\nArtist's Driver : Ramon Novellas\nDirector\"s Driver : Hector Molina\nRunner : Judith Gómez\nRunner : Juanjo Infante\nRunner : Miguel Angel Morales\nSet Manager : Gerard Argemí\nPOST-PRODUCTION - Paume:\nPost-Producer : Madeleine Kondé\nEditor : Marie-Charlotte Moreau\nColorist : Duncan Russell\nLOCATIONS:\nScouter : Ismael Garcia\n \nCAMERA:\nDOP : Oriol Barcelona\nStedicam Operator : Niko Lasarte\nFocus Puller : Hector Julian\nCamera Assistant : Roger Milian\nVTR : Joan Brusés\nDIT : Kike Molina\n \nLIGHT:\nGaffer : Xavier Carrión\nSpark : Pere Arnal\nSpark : Marc Canalda\nGRIP:\nKey Grip : David Arres\nGrip : Toni Espejo\nCamera Car : Josep Pujol\nDRONE:\nDrone FPV Pilot : Sergi Ros\nDrone Inspire Pilot : Adam Puig\nDrone Assistant : Sergi Barnils\n \nART DEPARTMENT:\nArt Director : Laia Serra\nArt Assistant : Olivia O'S\nSTYLIST DEPARTMENT:\nStylist : Ana Morera\nStylist Assistant : Júlia Puig\nStylist Assistant : Noemí Galí\nMAKE UP:\nMake Up : Ana Cano\nMake Up Assistant : Nuria Ribera\nMake Up Assistant : Raquel Garcia\n \nSOUND:\nSound : Arthur Cañameras\n \nNURSE:\nNurse on Set : María José Cortés\n\nLYRICS\n\nTu me Play\n\nTout n’est pas clair\nDans ce désert\nMais si je suis sur terre \nC’est pour te plaire\n\nJ’avais rien d’autre à moi que ma vie \nJ’avais rien d’autre à vie que ma voix \nJ’sautais dans les flaques\nJ’tapais dans le déluge\nJ’sautais dans les couacs\nComme un subterfuge\n\nT’as mis le feu là dans ma fête\nLe rodéo là, braaa, dans ma tête\nSur ton visage le présage d’une allumette\nPrésage d’une allumette\n\nAh ! Comme cet amour est beau ! Oh !\nAh ! Comme cet amour est haut, haut !\nAh ! Comme cet amour est haut ! Oh ! Ah !\n\nTout n’est pas clair\nDans ce désert\nMais si je suis sur terre\nC’est pour te plaire\nDans ce désert\nOui si je suis sur terre\nC’est que tu me play\n\nT’avais rien d’autre à toi que la nuit \nT’étais comme à la mort à la vie \nSauter dans les flaques\nÇa faisait des ratures\nTaper dans les couacs \nÇa faisait des coupures\n\nJ’ai mis le feu là dans ta fête\nLe Roméo là, braaa, dans ta tête\nSur mon visage le présage d’une allumette\nPrésage d’une allumette\n\nAh ! Comme cet amour est beau ! Oh ! Ah ! \nComme cet amour est haut ! Oh ! Ah !\nComme cet amour est haut ! Oh ! Ah !\n\nTout n’est pas clair \nDans ce désert\nMais si je suis sur terre\nC’est pour te plaire \nDans ce désert\nOui si je suis sur terre \nC’est que tu me play\n\nAh ! Comme cet amour est beau ! Oh !\nAh ! Comme cet amour est haut ! Oh !\nAh ! Comme cet amour est haut ! Oh !\nAh ! Comme cet amour est beau ! Oh !\nAh ! Comme cet amour est haut ! Oh !\n\nOui si je suis sur terre\nC’est que tu me play\n\n\nhttp://vevo.ly/2WDLNr",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/rl4QZL9SuDk/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/rl4QZL9SuDk/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/rl4QZL9SuDk/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "JulietteArmanetVEVO",
        tags: [
          "Armanet",
          "Juliette Armanet",
          "Juliette Armanet musique",
          "Juliette Armanet clip",
          "Juliette Armanet paroles",
          "Juliette Armanet lyrics",
          "Juliette Armanet tu me play",
          "Juliette Armanet tu me plais",
          "Juliette Armanet tu me play clip Juliette Armanet tu me plais clip",
          "Juliette Armanet tu me play paroles",
          "Juliette Armanet tu me plais paroles",
          "Juliette Armanet tu me play brûler le feu",
          "brûler le feu Juliette Armanet",
          "brûler le feu tu me play",
          "brûler",
          "feu",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "Juliette Armanet - Tu me Play (Clip Officiel)",
          description:
            "Nouvel album « Brûler le feu » maintenant disponible partout ❤️‍🔥https://lnk.to/JA-FeuID ❤️‍🔥\n \nS’abonner à la chaîne YouTube de Juliette : https://JulietteArmanet.lnk.to/abo-ytID\nInstagram : https://www.instagram.com/juliettearmanet\nFacebook : https://www.facebook.com/JulietteArmanet\nTwitter : https://twitter.com/juliettearmanet\nVinyle, CD, vêtements et accessoires : https://juliettearmanet.store/\n \n \nPRODUCTION - Caviar Paris:\nDirector : J.A.C.K\nExecutive Producer : Florent Haëse\nLine Producer  : Pierre Signoret\nChoregrapher : Carine Charaire\nCoach Roller : Rym Senoussi\nProduction Coordinator : Regine Yoba\nProduction Assistant : Manon Evrols\nProduction Assistant : Anna-Eva Sieger\n \n \nPRODUCTION SERVICE - Slime:\nExecutive Producer : Laia Vidal\nProducer : Imma Gutiérrez\n1st AD : Emilio Pérez\nLine Producer : Gemma Monzó\nProduction coordinator : Rocio Saiz\nArtist's Driver : Ramon Novellas\nDirector\"s Driver : Hector Molina\nRunner : Judith Gómez\nRunner : Juanjo Infante\nRunner : Miguel Angel Morales\nSet Manager : Gerard Argemí\nPOST-PRODUCTION - Paume:\nPost-Producer : Madeleine Kondé\nEditor : Marie-Charlotte Moreau\nColorist : Duncan Russell\nLOCATIONS:\nScouter : Ismael Garcia\n \nCAMERA:\nDOP : Oriol Barcelona\nStedicam Operator : Niko Lasarte\nFocus Puller : Hector Julian\nCamera Assistant : Roger Milian\nVTR : Joan Brusés\nDIT : Kike Molina\n \nLIGHT:\nGaffer : Xavier Carrión\nSpark : Pere Arnal\nSpark : Marc Canalda\nGRIP:\nKey Grip : David Arres\nGrip : Toni Espejo\nCamera Car : Josep Pujol\nDRONE:\nDrone FPV Pilot : Sergi Ros\nDrone Inspire Pilot : Adam Puig\nDrone Assistant : Sergi Barnils\n \nART DEPARTMENT:\nArt Director : Laia Serra\nArt Assistant : Olivia O'S\nSTYLIST DEPARTMENT:\nStylist : Ana Morera\nStylist Assistant : Júlia Puig\nStylist Assistant : Noemí Galí\nMAKE UP:\nMake Up : Ana Cano\nMake Up Assistant : Nuria Ribera\nMake Up Assistant : Raquel Garcia\n \nSOUND:\nSound : Arthur Cañameras\n \nNURSE:\nNurse on Set : María José Cortés\n\nLYRICS\n\nTu me Play\n\nTout n’est pas clair\nDans ce désert\nMais si je suis sur terre \nC’est pour te plaire\n\nJ’avais rien d’autre à moi que ma vie \nJ’avais rien d’autre à vie que ma voix \nJ’sautais dans les flaques\nJ’tapais dans le déluge\nJ’sautais dans les couacs\nComme un subterfuge\n\nT’as mis le feu là dans ma fête\nLe rodéo là, braaa, dans ma tête\nSur ton visage le présage d’une allumette\nPrésage d’une allumette\n\nAh ! Comme cet amour est beau ! Oh !\nAh ! Comme cet amour est haut, haut !\nAh ! Comme cet amour est haut ! Oh ! Ah !\n\nTout n’est pas clair\nDans ce désert\nMais si je suis sur terre\nC’est pour te plaire\nDans ce désert\nOui si je suis sur terre\nC’est que tu me play\n\nT’avais rien d’autre à toi que la nuit \nT’étais comme à la mort à la vie \nSauter dans les flaques\nÇa faisait des ratures\nTaper dans les couacs \nÇa faisait des coupures\n\nJ’ai mis le feu là dans ta fête\nLe Roméo là, braaa, dans ta tête\nSur mon visage le présage d’une allumette\nPrésage d’une allumette\n\nAh ! Comme cet amour est beau ! Oh ! Ah ! \nComme cet amour est haut ! Oh ! Ah !\nComme cet amour est haut ! Oh ! Ah !\n\nTout n’est pas clair \nDans ce désert\nMais si je suis sur terre\nC’est pour te plaire \nDans ce désert\nOui si je suis sur terre \nC’est que tu me play\n\nAh ! Comme cet amour est beau ! Oh !\nAh ! Comme cet amour est haut ! Oh !\nAh ! Comme cet amour est haut ! Oh !\nAh ! Comme cet amour est beau ! Oh !\nAh ! Comme cet amour est haut ! Oh !\n\nOui si je suis sur terre\nC’est que tu me play\n\n\nhttp://vevo.ly/2WDLNr",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT2M43S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        regionRestriction: {
          blocked: ["BY", "IO", "KP", "RU", "SS"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "74117",
        likeCount: "1981",
        favoriteCount: "0",
        commentCount: "141",
      },
    },
    {
      kind: "youtube#video",
      etag: "MSyqrzvDRvmDlZBq30Lf9LFS9ss",
      id: "h1fHTuiM5n0",
      snippet: {
        publishedAt: "2022-04-11T18:00:13Z",
        channelId: "UCZ8kV8vuMdDLSerCIFfWnFQ",
        title: "HOT ONES : Jonathan Cohen perd l’usage de sa langue",
        description:
          "Kyan Khojandi reçoit Jonathan Cohen à la table de Hot Ones. Et on l’avait jamais vu comme ça…\n\nCrédits Complex EP :\n\nJustin Killion\nChris Schonberger\nNick Wang\n\nBasé sur le programme “Hot Ones” créé par Complex Networks et First We Feast.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/h1fHTuiM5n0/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/h1fHTuiM5n0/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/h1fHTuiM5n0/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Studio Bagel",
        tags: [
          "studio bagel",
          "studio",
          "bagel",
          "humour",
          "comedie",
          "drole",
          "marrant",
          "sketch",
          "parodie",
          "jonathan cohen",
          "Kyan khojandi",
          "interview",
          "piment",
          "hot ones",
        ],
        categoryId: "23",
        liveBroadcastContent: "none",
        defaultLanguage: "fr",
        localized: {
          title: "HOT ONES : Jonathan Cohen perd l’usage de sa langue",
          description:
            "Kyan Khojandi reçoit Jonathan Cohen à la table de Hot Ones. Et on l’avait jamais vu comme ça…\n\nCrédits Complex EP :\n\nJustin Killion\nChris Schonberger\nNick Wang\n\nBasé sur le programme “Hot Ones” créé par Complex Networks et First We Feast.",
        },
        defaultAudioLanguage: "fr",
      },
      contentDetails: {
        duration: "PT33M19S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1208277",
        likeCount: "63561",
        favoriteCount: "0",
        commentCount: "1928",
      },
    },
    {
      kind: "youtube#video",
      etag: "omfABBADhbtoBg5Bdb-vGKXJLqA",
      id: "_2bbuDU74H4",
      snippet: {
        publishedAt: "2022-04-13T09:00:10Z",
        channelId: "UCVd0AALHLY9et-UU1r1m_Bw",
        title: "Ferre Gola - Royaume Kunga (Kingdom) (Official Music Video)",
        description:
          "Music video by Ferre Gola performing Royaume Kunga (Kingdom). (C) 2022 Sony Music Entertainment East Africa Limited\n\nhttp://vevo.ly/xxONNf",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/_2bbuDU74H4/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/_2bbuDU74H4/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/_2bbuDU74H4/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "FerreGolaVEVO",
        tags: [
          "Ferre Gola",
          "Ndombolo",
          "Royaume Kunga (Kingdom)",
          "Sony Music Entertainment East Africa Limited",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "Ferre Gola - Royaume Kunga (Kingdom) (Official Music Video)",
          description:
            "Music video by Ferre Gola performing Royaume Kunga (Kingdom). (C) 2022 Sony Music Entertainment East Africa Limited\n\nhttp://vevo.ly/xxONNf",
        },
      },
      contentDetails: {
        duration: "PT3M5S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        regionRestriction: {
          blocked: ["RU"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "400209",
        likeCount: "17931",
        favoriteCount: "0",
        commentCount: "3952",
      },
    },
  ],
  nextPageToken: "CBQQAA",
  pageInfo: {
    totalResults: 200,
    resultsPerPage: 20,
  },
};
